Correct function name in OMA-DM engine to match java function name.
This is to fix following error caused due to incorrect function name.
09-26 14:51:43.391  3769  3791 E AndroidRuntime: java.lang.NoSuchMethodError: 
no non-static method "Lcom/android/omadm/service/DMSession;
.getDmAlert()Lcom/android/omadm/service/DmAlert;"

Bug: 17754958
Change-Id: Ia6b8e5947239144dd148c86771babd6cfe2bafe9